# Generated by Django 5.0.7 on 2025-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History'), ('biography', 'Biography'), ('hinduism', 'Hindu Scripture / Spiritual Philosophy'), ('other', 'Other')], max_length=20),
        ),
    ]
